### ISSUE TITLE
Arquivo errado mencionado na explicação da flag --core

### ISSUE THREAD

**Issue by leolopes** [tray-tecnologia/tray-cli#1]
## Descrição

Na explicação sobre a flag `--core` do comando `upload`, é mencionado que se ignora o arquivo `settings.html`

## Detalhes

Porém, no código menciona o `settings.json`, que seria o que originalmente planejamos ignorar.

Também fala em ignorar a pasta de imagens inteiramente. Não lembro como era no plano original, mas no meu entendimento, a pasta que realmente precisaria ser ignorada é a `img/settings`.

==

No mais, legal que o projeto evoluiu para este novo! Pode ter certeza que contribuiremos!

**Comment by rhandrade** [comment]
@leolopes Muito obrigado pelo alerta. Já corrigi a questão do readme mencionar o arquivo errado `settings.html`. :tada:

Sobre a questão da pasta imagens, no antigo tray-theme tínhamos feito para ele remover a pasta imagens completamente, não subindo nenhuma imagem mesmo. Isso faz sentido, pois as vezes não queremos poluir com imagens que não serão nem usadas em um novo tema.

**Comment by leolopes** [comment]
De acordo!
