### ISSUE TITLE
Baixo feedback de processos de upload de arquivos em massa

### ISSUE THREAD

**Issue by leolopes** [tray-tecnologia/tray-cli#10]
### Descrição

Ao fazer upload de arquivos em massa com `upload` ou `upload --core`, não temos ideia do progresso da tarefa.

### Motivo

Durante o progresso de upload, é mostrada uma mensagem com spinner indicando que o upload está sendo feito. Porém, não sabemos quais arquivos já subiram ou estão subindo. Apenas somos avisados, ao final do processo, dos arquivos que não subiram.

### Comportamento esperado

- A interface poderia logar cada um dos arquivos durante seu upload e após o upload, indicando sucesso ou erro,
- ou, no mínimo, poderia exibir o arquivo que está subindo no momento,
- e/ou exibir o número do arquivo na fila (ex: Subindo arquivo 1 de 150)
- e logar os erros todos à medida em que acontecem, a fim de o usuário ter a oportunidade de interromper o processo no meio, caso haja um erro.

**Comment by rhandrade** [comment]
@leolopes essa foi uma troca que fizemos para poder oferecer um melhor envio das informações. Atualmente as informações são enviadas de forma assíncrona, ou seja ele pode disparar vários arquivos simultaneamente, aumentando a velocidade de upload e diminuindo o tempo necessário. Deixar a exibição por linha / arquivo gera outputs equivocados complicados de tratar.

Entendemos que para temas com muitos arquivos (que compreende a maioria dos temas) o processo síncrono demorava muito e saber que o arquivo deu erro na hora não era muito vantajoso, pois em uma situação que o arquivo a dar erro fosse o último, o tempo de espera seria muito maior.

Entendemos que a implementação atual sana o problema de saber quais arquivos deram erro, e ainda melhora em muito, o tempo necessário para o envio. Em testes feitos um tema caiu de 1 minuto para 20s.

**Comment by leolopes** [comment]
Entendi, @rhandrade , e concordo com a abordagem. Realmente melhorou muito o tempo de upload :)
Só não estou lembrado agora se, ao final do processo, os arquivos que geraram erro são realmente listados por nome, ou se só indica quantos arquivos falharam.
