### ISSUE TITLE
Erro ao tentar fazer download de vários arquivos por "glob"

### ISSUE THREAD

**Issue by leolopes** [tray-tecnologia/tray-cli#11]
### Descrição

Ao tentar fazer o download de vários arquivos usando padrões de _glob_, apresenta o erro:

> Unable to process request. Please try again in few moments.

![Captura de tela da CLI mostrando erro ao tentar baixar múltiplos arquivos com glob](https://user-images.githubusercontent.com/2057740/192352392-e1d58a6d-c467-4ccf-8ffb-caa8f906cecc.png)

### Motivo

Utilizamos padrões _glob_ para fazer upload de pastas inteiras, tipos de arquivo específicos, etc, o que economiza tempo e dados, uma vez que não são subidos todos os arquivos de uma vez.

Porém, ao tentar fazer a mesma coisa no processo de download, não conseguimos. Isso é até pior do que não poder fazê-lo no upload, pois pressupõe que nós saibamos de antemão os nomes dos arquivos, e que são poucos o suficiente para podermos fazer um por um.

Acabamos tendo de fazer download de todo o tema para economizar tempo.

_Outro problema_ ainda é o fato de que a mensagem de erro não corresponde necessariamente ao erro, de modo que o usuário pode achar que seja apenas uma instabilidade.

### Comportamento Esperado

Que ao utilizar padrões de _glob_ no comando `try download`, sejam baixados os arquivos que correspondam ao padrão, assim como acontece no upload.

**Comment by rhandrade** [comment]
@leolopes nem o comando nem a api de **download** suportam os padrões glob. Quando fomos desenvolver entendemos que não fazia sentido baixar somente uma parte do tema. 

A ideia do comando download é baixar um ou outro arquivo para uma validação rápida ou todo o tema. Baixar porções inteiras do tema como o `configs` ou o `elements` não faz sentido para nós.

Por exemplo, baixar somente os arquivos da pasta `elements` não fariam o tema funcionar, bem como os configs, layouts e pages. Para ele funcionar precisa de todos os arquivos. No caso do upload faz pois presume-se que todos os arquivos já foram enviados pelo menos uma vez e já estão la, e se eu alterei os arquivos X, Y e Z não teria porque enviar todo o tema novamente.

**Comment by leolopes** [comment]
@rhandrade então, eu tenho vários momentos em que preciso baixar apenas uns poucos arquivos, apesar de ser uma situação mais rara do que o contrário (subir poucos os arquivos). Acredito que deva variar bastante com a forma de trabalho de cada desenvolvedor.

De qualquer modo, se a API não suporta os padrões de glob, nem teria o que fazer antes de essa API ser alterada.

Obrigado

**Comment by leolopes** [comment]
Olá @rhandrade , tudo bem?
Vi que estão fechando as issues por conta da nova versão, e que aparentemente também tem uma nova versão da API saindo, certo?

Com base nisso, aproveito pra perguntar se esta questão aqui pode ser resolvida com a nova API.
Obrigado!

**Comment by rhandrade** [comment]
@leolopes Nesse momento essa funcionalidade ainda não é suportada pela API. É possível fazer a implementação somente do lado do CLI usando os endpoints atuais. Se quiser contribuir será bem vindo e posso mergear depois.
