### ISSUE TITLE
Comando Tray Watch não funcionando

### ISSUE THREAD

**Issue by guiibraun** [tray-tecnologia/tray-cli#13]
Olá, estou tendo um problema com o comando "tray watch", toda vez que eu inicio ele encerra sozinho instantaneamente. Tentei ativar o debug porém não ta gerando nenhum log

![image](https://user-images.githubusercontent.com/65604906/204515743-8ddc3e54-6e1b-462f-b2d9-260476641c62.png)

**Comment by guiibraun** [comment]
![image](https://user-images.githubusercontent.com/65604906/204515704-65e621be-5f96-4dcd-8147-70a295ec1dd0.png)

**Comment by allanstanichescki** [comment]
Estou com o mesmo problema, você conseguiu resolver isso?

**Comment by rhandrade** [comment]
@guiibraun Qual sistema vc está usando? Consegui simular aqui no Linux, mas só para entender se é ago relacionado ao sistema operacional ou geral do Chokidar.

**Comment by guiibraun** [comment]
Opa, to usando Windows 11 msm.

**Comment by rhandrade** [comment]
Subi uma correção no MR #14 que deve corrigir esse problema @guiibraun. Obrigado por reportar.

**Comment by christian-alves** [comment]
![image](https://github.com/user-attachments/assets/f01bd6f0-c2d6-476d-9e1c-c41b3d434643)
![image](https://github.com/user-attachments/assets/12b79318-80d5-4b64-8638-60bd9bfc2af3)

Problema ainda acontecendo no meu Windows 11. 
Usando powershell, e windows powershell. 
CLI Tray V 1.1.2;
