### ISSUE TITLE
Erro no upload de arquivos

### ISSUE THREAD

**Issue by diegosouz4** [tray-tecnologia/tray-cli#15]
É apresentado erro ao tentar fazer o upload de arquivos, tanto utilizando o "tray watch" quanto o "tray upload [..files]". Sempre o mesmo erro `"Could not update file [...file] due to error - Unable to process request. Please try again in few moments."`. 

Segue info do --debug:

`[10/03/2023, 10:54:06] Type: Error | Operation: sendThemeAsset | Data: {"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400\n    at createError (/home/diegosouza/.nvm/versions/node/v19.3.0/lib/node_modules/@tray-tecnologia/tray-cli/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/home/diegosouza/.nvm/versions/node/v19.3.0/lib/node_modules/@tray-tecnologia/tray-cli/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/home/diegosouza/.nvm/versions/node/v19.3.0/lib/node_modules/@tray-tecnologia/tray-cli/node_modules/axios/lib/adapters/http.js:312:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"headers":{"Accept":"application/json","Content-Type":"application/json","Authorization":"Token token=XXXXXXXXXXXXXX","User-Agent":"@tray-tecnologia/opencode-sdk@1.0.0","Content-Length":5228},"url":"https://opencode.tray.com.br/api/themes/33/assets","method":"put","data":"{\"gem_version\":\"1.0.4\",\"key\":\"/css/sass/footer.scss\",\"value\":\"LmZvby1jb250ZW50ewogICAgYmFja2dyb3VuZDogI2ZmZjsKICAgIGJvcmRlci10b3A6IDFweCBzb2xpZCAjZTJlMmUyOwogICAgbWFyZ2luLXRvcDogMzBweDsKICAgIHBhZGRpbmc6IDMwcHggMDsKICAgIAogICAgaDN7CiAgICAgICAgY29sb3I6ICM4YzhjOGM7CiAgICAgICAgbWFyZ2luLWJvdHRvbTogMjBweDsKICAgICAgICB0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlOwogICAgICAgIAogICAgICAgIEBpbmNsdWRlIHR5cG8oMS44cmVtLCA3MDAsICRmb250LCAycmVtKTsgCiAgICB9CiAgICAKICAgIGg1ewogICAgICAgIGNvbG9yOiAjOGM4YzhjOwogICAgICAgIG1hcmdpbjogNXB4IDA7CiAgICAgICAgcGFkZGluZzogMCAwIDAgNXB4OwogICAgICAgIHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7CiAgICAgICAgCiAgICAgICAgQGluY2x1ZGUgdHlwbygxcmVtLCA3MDAsICRmb250LCAxLjVyZW0pOwogICAgfQogICAgCiAgICAubGlua3MtbGlzdHsKICAgICAgICAKICAgICAgICBsaXsKICAgICAgICAgICAgbWFyZ2luLWJvdHRvbTogMTBweDsKICAgICAgICB9CiAgICAgICAgCiAgICAgICAgYXsKICAgICAgICAgICAgY29sb3I6ICM4YzhjOGM7CiAgICAgICAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jazsgCiAgICAgICAgICAgIAogICAgICAgICAgICBAaW5jbHVkZSB0eXBvKDEuNHJlbSwgMzAwLCAkZm9udCwgMS42cmVtKTsKICAgICAgICB9CiAgICB9CiAgICAKICAgIC5zb2NpYWwtbGlzdHsKICAgICAgICAKICAgICAgICAuc29jaWFsLWxpc3R7CiAgICAgICAgICAgIAogICAgICAgICAgICBsaXsKICAgICAgICAgICAgICAgIG1hcmdpbi1ib3R0b206IDE1cHg7CiAgICAgICAgICAgIH0KICAgICAgICAgICAgCiAgICAgICAgICAgIGF7CiAgICAgICAgICAgICAgICBkaXNwbGF5OiBibG9jazsKICAgICAgICAgICAgICAgIGZvbnQtc2l6ZTogMS42cmVtOwogICAgICAgICAgICAgICAgbGluZS1oZWlnaHQ6IDIwcHg7CiAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICY6aG92ZXIsCiAgICAgICAgICAgICAgICAmOmZvY3VzewogICAgICAgICAgICAgICAgICAgIHRleHQtZGVjb3JhdGlvbjogbm9uZTsKICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgaW1newogICAgICAgICAgICAgICAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jazsKICAgICAgICAgICAgICAgICAgICBtYXJnaW4tcmlnaHQ6IDVweDsKICAgICAgICAgICAgICAgICAgICB2ZXJ0aWNhbC1hbGlnbjogdG9wOwogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9CiAgICAgICAgfQogICAgfQogICAgCiAgICAucGF5bWVudC1nYXRld2F5c3sKICAgICAgICAKICAgICAgICBAbWVkaWEgKG1pbi13aWR0aDogNzY4cHgpIGFuZCAobWF4LXdpZHRoOiA5OTFweCl7CiAgICAgICAgICAgIGNsZWFyOiBsZWZ0OwogICAgICAgIH0KICAgICAgICAKICAgICAgICAucGF5bWVudC1mb3JtewogICAgICAgICAgICBwYWRkaW5nOiAzcHg7CiAgICAgICAgICAgIAogICAgICAgICAgICBpbWd7CiAgICAgICAgICAgICAgICBtYXgtaGVpZ2h0OiAyN3B4OwogICAgICAgICAgICB9CiAgICAgICAgfQogICAgICAgIAogICAgICAgIC5yb3d7CiAgICAgICAgICAgIG1hcmdpbi1sZWZ0OiAtM3B4OwogICAgICAgICAgICBtYXJnaW4tcmlnaHQ6IDA7CiAgICAgICAgfQogICAgICAgIAogICAgICAgIHN2Z3sKICAgICAgICAgICAgbWF4LXdpZHRoOiAxMDAlOwogICAgICAgIH0KICAgICAgICAKICAgICAgICAuc2VjdXJpdHktdGl0bGV7CiAgICAgICAgICAgIG1hcmdpbi10b3A6IDIwcHg7CiAgICAgICAgfQogICAgfQogICAgCiAgICBAbWVkaWEgc2NyZWVuIGFuZCAobWF4LXdpZHRoOiAkc20pewogICAgICAgIAogICAgICAgIC5jb250YWluZXIgPiBkaXZ7CiAgICAgICAgICAgIG1hcmdpbi10b3A6IDcwcHg7CiAgICAgICAgICAgIAogICAgICAgICAgICAmOmZpcnN0LWNoaWxkewogICAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMDsKICAgICAgICAgICAgfQogICAgICAgIH0KICAgIH0KfQoKLmZvby1wYXltZW50ewogICAgbWF4LXdpZHRoOiAzMjBweDsKfQoKLmZvby1jb250YWN0ewogICAgCiAgICBAbWVkaWEgc2NyZWVuIGFuZCAobWluLXdpZHRoOiA3NjhweCkgYW5kIChtYXgtd2lkdGg6IDk5MnB4KXsKICAgICAgICBtYXJnaW4tYm90dG9tOiA3MHB4OwogICAgfQogICAgCiAgICBpewogICAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jazsKICAgICAgICBmb250LXNpemU6IDA7CiAgICAgICAgaGVpZ2h0OiAzNnB4OwogICAgICAgIG1hcmdpbi1yaWdodDogMTBweDsKICAgICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7CiAgICAgICAgdmVydGljYWwtYWxpZ246IG1pZGRsZTsKICAgICAgICB3aWR0aDogMzZweDsKICAgICAgICAKICAgICAgICBAbWVkaWEgKG1pbi13aWR0aDogOTkycHgpewogICAgICAgICAgICBkaXNwbGF5OiBub25lOwogICAgICAgIH0KICAgICAgICAKICAgICAgICBAbWVkaWEgKG1pbi13aWR0aDogMTIwMHB4KXsgICAKICAgICAgICAgICAgZGlzcGxheTogaW5saW5lLWJsb2NrOwogICAgICAgIH0KICAgICAgICAKICAgICAgICBAbWVkaWEgKG1heC13aWR0aDogNzY3cHgpeyAgIAogICAgICAgICAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7CiAgICAgICAgfQogICAgICAgICAgICAKICAgICAgICAmOmJlZm9yZXsKICAgICAgICAgICAgY29udGVudDogJyc7CiAgICAgICAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jazsKICAgICAgICAgICAgaGVpZ2h0OiAzNnB4OwogICAgICAgICAgICB2ZXJ0aWNhbC1hbGlnbjogbWlkZGxlOwogICAgICAgICAgICB3aWR0aDogMSU7CiAgICAgICAgfQogICAgICAgIAogICAgICAgIHN2Z3sKICAgICAgICAgICAgZGlzcGxheTogaW5saW5lLWJsb2NrOwogICAgICAgICAgICBmaWxsOiAjOWU5ZTllOwogICAgICAgICAgICBtYXgtd2lkdGg6IDk5JTsKICAgICAgICAgICAgdmVydGljYWwtYWxpZ246IG1pZGRsZTsKICAgICAgICB9CiAgICB9CiAgICAKICAgIHB7CiAgICAgICAgY29sb3I6ICM4YzhjOGM7CiAgICAgICAgZGlzcGxheTogaW5saW5lLWJsb2NrOwogICAgICAgIHZlcnRpY2FsLWFsaWduOiBtaWRkbGU7CiAgICAgICAgd2lkdGg6IDgwJTsKICAgICAgICBAaW5jbHVkZSB0eXBvKDEuNHJlbSwgNDAwLCAkZm9udCwgMS44cmVtKTsKICAgIH0KICAgIAogICAgbGl7CiAgICAgICAgbWFyZ2luLXRvcDogMTdweDsKICAgICAgICAKICAgICAgICAmOmZpcnN0LWNoaWxkewogICAgICAgICAgICBtYXJnaW4tdG9wOiAwOwogICAgICAgIH0KICAgIH0KfQoKLmZvby1zZWFsc3sKICAgIAogICAgPiBsaXsKICAgICAgICBtYXJnaW4tYm90dG9tOiAxMHB4OwogICAgfQogICAgCiAgICAuc2VhbC1lYml0ewogICAgICAgIG1hcmdpbi1yaWdodDogMTBweDsKICAgIH0KICAgIAogICAgY2VudGVyewogICAgICAgIHRleHQtYWxpZ246IGxlZnQ7CiAgICB9CiAgICAKICAgIC5nb29nbGUtc2FmZXsKICAgICAgICBiYWNrZ3JvdW5kOiAjZmZmOwogICAgICAgIGJvcmRlci1yYWRpdXM6IDNweDsKICAgICAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7CiAgICAgICAgcGFkZGluZzogM3B4OwogICAgICAgIHdpZHRoOiAxMTVweDsKICAgIH0KfQoKLmZvby1tZXNzYWdlewogICAgYmFja2dyb3VuZDogI2ZmZjsKICAgIGNvbG9yOiAjOGM4YzhjOwogICAgbWFyZ2luOiAxcHggMCAxNXB4OwogICAgcGFkZGluZzogMjVweCAwOwogICAgdGV4dC1hbGlnbjogY2VudGVyOwogICAgCiAgICBAaW5jbHVkZSB0eXBvKDEuMnJlbSwgNDAwLCAkZm9udCwgMS42cmVtKTsKICAgIAogICAgLm1lc3NhZ2UtZm9vdGVyIHsKICAgICAgICBjb2xvcjogIzhjOGM4YzsKICAgIH0KfQ==\"}"},"status":400}`

**Comment by rhandrade** [comment]
@diegosouz4 Geralmente esses erros acontecem devido ao conteúdo enviado no arquivo. Repare no status code 400. Verifique o conteúdo do arquivo para tentar novamente.
