### ISSUE TITLE
Impossível utilizar a API do Tray CLI com um gulpfile na raiz do Draft Theme

### ISSUE THREAD

**Issue by leolopes** [tray-tecnologia/tray-cli#18]
### Descrição

Não conseguimos subir arquivos pela API do Tray CLI com um gulpfile localizado na raiz do tema Draft.

### Motivo

O motivo é que, ao passar um path que inclua a pasta `/theme` (necessária para encontrar o arquivo), a validação de pastas do Tray CLI não permite o upload.

### Detalhes

Estamos desenvolvendo um tema novo baseado no [Draft Partner Theme](https://github.com/tray-tecnologia/draft-partner-theme), usando a base da estrutura de pastas desse tema.

Por causa de problemas envolvendo o [upload do mesmo arquivo múltiplas vezes](https://github.com/tray-tecnologia/tray-cli/issues/4) quando compilado, resolvemos usar a API para fazer o upload apenas quando queremos.

**Porém, notamos um problema:** suponha a seguinte estrutura de pastas:
```
Draft Theme/
├─ theme/
│  ├─ elements/
│  │  ├─ product.html
├─ gulpfile.js

```
A partir do gulpfile, o path do arquivo product.html é `./theme/elements/product.html`

Se eu tentar fazer um upload desse path, ocorre um erro do tipo `FolderNotAllowedError`
Eu suponho que seja por causa do `/theme` no início do path.

Pois bem, entendendo isso, tentei fazer um replace, tirando o `/theme` do path antes de fazer o upload. O problema é que daí o arquivo não é mais encontrado (erro `LoadThemeAssetError`).

A única coisa que funcionou foi passar o gulpfile.js para dentro da pasta `/theme`, porém, isso não é o ideal, pois muda muito a estrutura original do Draft Theme. Acabamos fazendo um gulpfile separado só para o usar a API do Tray CLI, esse sim, dentro da pasta `theme`.

### Comportamento esperado

Deveria haver algum parâmetro no upload para indicar qual é a pasta raiz a ser considerada. **Ex:** se eu declarar a pasta `theme` como raiz, ao passar um path `theme/elements/product.html`, a pasta `theme` deveria ser ignorada na validação.

**Comment by rhandrade** [comment]
@leolopes para o fluxo funcionar corretamente precisamos saber com toda a certeza quais são os arquivos do tema. Você pode solucionar esse comportamento rodando separadamente o gulp na pasta principal e o Tray CLI na pasta theme que assim que o gulp finalizar a escrita dos arquivos o mesmo será enviado usando o Tray CLI.

**Comment by leolopes** [comment]
Bom dia @rhandrade , foi exatamente o que fiz, apesar de considerar uma solução abaixo do ideal, pois seria possível modificar o comando para considerar uma raiz diferente, como sugeri na abertura da issue.
