### ISSUE TITLE
Interesse em contribuir e duvida sobre a CLI

### ISSUE THREAD

**Issue by LuizFelipeOliver** [tray-tecnologia/tray-cli#19]
Olá atualmente estou trabalhando em um sistemas de automação de deploy utilizando a CLI, gostaria que me tirasse uma duvida sobre o motivo de quando é gerado o arquivo config.yml o **ID** do tema é gerado como string sendo que no sdk mostra que é aceito number(Ela funciona normalmente é somente uma duvida sobre o porque).
Também tenho interesse de criar um interface TUI para a ferramenta, gostaria de saber se isso é de interesse de vocês

**Comment by rhandrade** [comment]
@LuizFelipeOliver Ele salva como string devido a uma limitação da biblioteca que estamos usando, entretanto internamente o id do tema sempre deverá ser um number.

Sobre a interface, nesse momento não temos previsão de adicionar essa funcionalidade, mas caso você a desenvolva, pode abrir um PR para que possamos validar, contudo não é um prioridade.
