### ISSUE TITLE
Idéia

### ISSUE THREAD

**Issue by juanfariasdev** [tray-tecnologia/tray-cli#2]
Seria muito interessante ter a opção de trabalhar com o tema da tray localmente. Assim ficaria bem mais rápido o desenvolvimento usando o VScode ~Se já existir, peço desculpas

**Comment by juanfariasdev** [comment]
Penso em algo 100% local, nem que seja com dados fakes. Pois daria para desenvolver sem depender dos servidores da tray.
Por exemplo, dentro do tema tem a opção de baixa-lo como zip. Seria muito interessante conseguir abri-lo localmente ou algo do tipo

**Comment by juanfariasdev** [comment]
Acredito que talvez se conseguir criar uma API que forneça os dados necessários, daria para instalar o Twig localmente. Estou dando uma lida na documentação dele e vendo como funciona o consumo a API

**Comment by rhandrade** [comment]
@juanfariasdev Entendi a ideia, e seria muito legal, entretanto seria complicado igualar o ambiente online e o ambiente local, e fazer toda essa simulação. E ai poderia acontecer de um código feito localmente poderia não funcionar no ambiente online. 

Hoje o CLI do Shopify possui desenvolvimento local, mas ele ainda precisa interação com os servidores da plataforma para fazer a sincronização dos dados e templates.

Acho que poderíamos tentar fazer a parte do `css` e `js` ser servida localmente enquanto desenvolve, mas toda a stack não creio que seja possível.

**Comment by rhandrade** [comment]
@juanfariasdev O maior problema não é puxar os dados, mas sim replicar o ambiente online localmente, pois não envolve somente o Twig. A Tray faz uso de funções e filtros que não são nativos e estão disponíveis somente no ambiente de produção. 

Além disso precisaria simular toda a stack de servidor para que quando o código Twig rodasse no ambiente local tivesse o mesmo comportamento que o online.

Hoje, infelizmente, isso não é possível.
