### ISSUE TITLE
Problema com as saindas do stdout e stderr ao rodar os comandos 

### ISSUE THREAD

**Issue by LuizFelipeOliver** [tray-tecnologia/tray-cli#22]
Encontrei um erro referente ao logs de saindo do comandos aparentemente eles estão todos saindo em stderr, não tendo uma separação entre stdout e stderr, aparentemente isso é por causa do ora.

Gostaria de saber se está é a forma como deve funcionar ?

points abaixo:

erro no comando:
![image](https://github.com/user-attachments/assets/0ba4ffa2-add5-411b-8cbf-ae7ecfdd6b45)

sucesso no comando:
![image(1)](https://github.com/user-attachments/assets/2db381a4-904e-43f8-9aa0-28720388b59c)

**Comment by rhandrade** [comment]
@LuizFelipeOliver Aparentemente essa é uma limitação do [Ora](https://github.com/sindresorhus/ora/tree/main?tab=readme-ov-file#stream). Por padrão ele irá jogar tudo para o `process.stderr`. Seria possível jogar para o stdout, mas não seria possível separar como deseja fazer acima.

Fechando a issue por não se tratar de um problema do CLI e sim de pacotes terceiros.
