### ISSUE TITLE
Dúvida sobre arquivos scss

### ISSUE THREAD

**Issue by joaoghummel** [tray-tecnologia/tray-cli#3]
Pelo que me lembre o opencode_theme, fazia também a parte de transformar o `scss` para `css` e também subia arquivos `scss`. Esse novo CLI não sobe arquivos `scss` e nem transforma para `css`.
É assim que deveria funcionar de fato ou pode ser que tenha algo errado, no setup?

Não que seja um problema, só para saber se o processo de build deveria ser de fato nosso mesmo.

**Comment by rhandrade** [comment]
Olá @joaoghummel, tudo certo? Espero que sim.

O opencode_theme antigo não compilava o `scss` para `css`. O que existia era o _**opencode workflow**_, um outro projeto open source da Tray que usava o `Gulp` para fazer a compilação localmente do `scss` para `css` e então enviar para os servidores da Tray. Esse projeto não está mais disponível.

O Tray CLI realmente **não** compila o `scss` para `css`, mas ele consegue enviar os arquivos para os servidores da Tray. O que acontece atualmente, e você pode verificar usando a opção `debug` no arquivo de configuração, é que o envio dos arquivos `scss` retornam erro devido a resposta dos servidores da Tray e não por causa da implementação desse novo CLI. Estamos trabalhando para corrigir esse problema no servidor.

Sobre a compilação do `scss`, em breve iremos depreciar essa funcionalidade dos servidores da Tray, bem como o recebimento dos arquivos `scss`. Essa medida irá gerar diversos benefícios, tanto para os parceiros quanto para a Tray: 

- Os parceiros terão a liberdade de usar o compilador mais atual e usufruir de novidades ainda não disponíveis nos servidores da Tray, gerando um código css mais limpo e otimizado. 
- A Tray poderá focar seus esforços em melhorar as outras tecnologias envolvidas no desenvolvimento das lojas, nas documentações para os parceiros, no suporte e relacionamento.

Espero que isso tenha esclarecido a questão 🙂.

**Comment by joaoghummel** [comment]
Show, obrigado pela resposta, concordo com tudo o que falou, não acho de fato necessário ficar subindo os arquivos `scss` para a plataforma.
Parabéns pela atualização dessa ferramenta que simplifica o fluxo de desenvolvimento usando tecnologias mais atuais, sem tem que ficar instalando o ruby, é ótimo para nós.
