### ISSUE TITLE
Repetição no envio de assets

### ISSUE THREAD

**Issue by Merieli** [tray-tecnologia/tray-cli#4]
> **Descrição**
>
> _Quando assets são modificados automaticamente com gulp ocorre repetição no envio dos arquivos no Tray CLI._
>
> **Motivo**
>
> _Repetição do mesmo arquivo._
>
> **Detalhes**
>
> _O envio ocorre 4 vezes para cada arquivo ._
>
> **Comportamento esperado**
>
> _Os assets deveriam ser enviados apenas uma única vez ao ser modificado._
>
> **Comportamento encontrado**
>
> _Assets minificados e não minificados são enviados várias vezes._

**Comment by albreis** [comment]
Utiliza só gulp sem o watch da API, provavelmente o teu gulp também está executando o mesmo comando que o watch do CLI já executa.

No meu workflow ta funcionando corretamente https://github.com/albreis/workflow-tray-cli

**Comment by rhandrade** [comment]
@albreis No caso o nosso gulp não aciona a API do Tray CLI, o nosso ainda está separado, precisando executar o `gulp` para verificar os arquivos e compilar os assets e o `tray watch` pra enviar os arquivos para a Tray.

Vimos que quando ele executa o código do `tray watch` duas vezes, uma pelo salvamento manual, trigado quando salva o arquivo, e o segundo quando o gulp acaba de compilar os arquivos.

Aliás muito maneiro seu workflow integrado, queremos criar algo semelhante em breve :)

Precisamos garantir que esse comportamento não aconteça quando executado em separado para otimizar o envio de recursos e não penalizar os servidores da plataforma.

**Comment by rhandrade** [comment]
Devido a criação de uma nova versão, validamos e o problema não parece mais acontecer. Irei fechar essa issue.
