### ISSUE TITLE
Erro upload sass

### ISSUE THREAD

**Issue by albreis** [tray-tecnologia/tray-cli#5]
Funcionou corretamente por algum tempo mas derepente começou a dar esse erro ao tentar enviar os arquivos .sass

**[UnknownError] [SDK::9999]: Unable to process request. Please try again in few moments**

Tanto usando direto no cli quanto via api no gulp

**Comment by rhandrade** [comment]
Olá @albreis... Esse é um problema conhecido e não está relacionado com o cli em si, mas sim com o servidor que processas as requisições que o CLI envia. Ele está com erro no processamento de arquivos `.sass`. Estamos verificando a melhor maneira de atuar sobre isso.

Atualmente recomendamos que **não** envie mais arquivos `.sass` para o servidores da Tray para serem compilados remotamente ou só para serem armazenados no tema. A compilação local dos assets traz diversos benefícios, como maior agilidade, melhor compatibilidade, novos recursos de novas versões do sass, entre outros. Para versionamento recomendamos usar algum software git, como o Github, Gitlab ou Bitbucket, otimizando o fluxo de desenvolvimento.

A compilação de `.sass` na plataforma já está depreciadas e em breve iremos remover esse recurso.
Conto com sua compreensão :)
