### ISSUE TITLE
Falha ao subir tema

### ISSUE THREAD

**Issue by karanguilherme** [tray-tecnologia/tray-cli#6]
Quanto tento subir um tema completo com tray upload exibe a falha abaixo:

⚠ Folder paths are not supported and will be ignored.
✖ TypeError: glob_1.default.sync(...).flat is not a function

**Comment by karanguilherme** [comment]
Rafa, resolvi o problema atualizando meu Node seguindo esse passo a passo, vou deixar documentado aqui para futuras consultas.



Primeiro, instalaremos o PPA para obter acesso aos pacotes dele. Do seu diretório home, utilize o curl para recuperar o script de instalação para sua versão de preferência, certificando-se de substituir o 14.x pela string da sua versão favorita (se for diferente):

cd ~
curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
Consulte a [documentação do NodeSource](https://github.com/nodesource/distributions/blob/master/README.md) para obter mais informações sobre as versões disponíveis.

Verifique o conteúdo do script baixado com o nano (ou seu editor de texto preferido):

nano nodesource_setup.sh
Assim que estiver satisfeito que o script está seguro para ser executado, saia do seu editor e, em seguida, execute o script com o sudo:

sudo bash nodesource_setup.sh
O PPA será adicionado à sua configuração e seu cache de pacotes local será atualizado automaticamente. Agora, você pode instalar o pacote Node.js da mesma forma que fez na seção anterior:

sudo apt install nodejs
Verifique se você instalou a nova versão executando o node com o sinalizador de versão -v:

node -v
Output
v14.2.0

**Comment by rhandrade** [comment]
Vlw @karanguilherme... Esqueci de colocar as versões que o Tray CLI suporte do Node.js. 

Vou adicionar na documentação para que todo mundo fique ciente quando for instalar. Vlw o toque e ajuda com a instalação caso alguém precise. :+1:
