### ISSUE TITLE
Comandos de upload tentam enviar pastas do node_modules

### ISSUE THREAD

**Issue by leolopes** [tray-tecnologia/tray-cli#9]
### Descrição

Ao fazer upload de arquivos em massa com `upload` ou `upload --core`, o comando tenta subir a pasta **node_modules**

### Motivo

Existem regras sobre quais pastas podem subir ou não para o tema, e se elas não podem ser subidas, deveriam ser ignoradas. Uma vez que a pasta **node_modules** é uma pasta que pode estar presente em projetos que instalem a CLI localmente, é uma pasta que pode inclusive ter uma regra específica para que nunca seja tentado seu upload.

O problema de tentar subi-la é que ela possui geralmente muitos arquivos, o que cria um relatório de erros muito grande.

### Comportamento esperado

A pasta **node_modules** pode ser totalmente ignorada, de preferência com alguma mensagem que explique por que ela está sendo ignorada.

**Comment by rhandrade** [comment]
@leolopes a pasta `node_modules` deve ser colocada uma pasta antes das pastas e arquivos do tema, ou seja, a pasta do tema não pode ser a mesma pasta do projeto node, na qual contem o node_modules e o package.json. **Isso não é permitido**.

O tema possui uma estrutura bem definida, mapeada em [nossa documentação](https://partners.tray.com.br/v/themes/construindo-seu-template/visao-geral/estrutura-do-tema) e o CLI espera essa estrutura de pastas e arquivos.

Se existirem outras pastas ou arquivos eles indicarão erro e não serão enviados. Isso é feito pois o desenvolvedor pode acidentalmente ter criado uma pasta ou arquivo no local errado e não ter percebido. Se ignorássemos os arquivos diferentes da lista padrão o desenvolvedor não saberia e demoraria a encontrar o erro.

Portanto, se precisa de bibliotecas do node, o tema deve ficar em uma pasta separada do node_modules. Ex:
```
- node_modules
- theme
    - configs
    - css
    - elements
    - img
    - layouts
    - pages  
```

**Comment by leolopes** [comment]
Entendi, a CLI então está adaptada à essa estrutura do tema Draft, pelo que entendi.
Faz sentido, obrigado!
